### ISSUE TITLE
Define custom message from deploy.rb

### ISSUE THREAD

**Issue by jaymecd** [ndbroadbent/capistrano_deploy_lock#3]
It would be really good to have ability to overwrite default message for deploy:create_lock with custom one

**Comment by ndbroadbent** [comment]
You can do this by running `cap deploy:lock`, and it will ask you for the custom lock message.

**Comment by jaymecd** [comment]
For manual lock yes, no problem I know.
I'd like to have possibility to customize message for regular deployment:

``` ruby
set :lock_message, "Deploying #{branch} branch"
```

but its failed, cause `:lock_message` is not allowed to set in deploy.rb
P.S. I'm but ruby developer

**Comment by ndbroadbent** [comment]
Ah, you can do this in `deploy.rb`:

```
set(:lock_message) { "Deploying #{branch} branch - custom message" }
```

The `branch` variable will not be evaluated until later.
